CREATE TABLE WeightRecords (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    ApplicationNo NVARCHAR(100) NOT NULL,
    VehicleNo NVARCHAR(100) NOT NULL,
    ItemNo NVARCHAR(100) NOT NULL,
    Weight FLOAT NOT NULL,
    ImagePath NVARCHAR(500) NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE()
);
